### ISSUE TITLE
Why using both bloc and provider? 

### ISSUE THREAD

**Issue by shamxali** [YamamotoDesu/advicer#1]
`provider: ^6.0.5
  flutter_bloc: ^8.1.2`

**Comment by YamamotoDesu** [comment]
@shamxali Thanks for commenting, Shams.
As you pointed out, generally we should use only one.

This content is from Udemy, [Dart & Flutter - Zero to Mastery [2023] + Clean ArchitectureDart & Flutter - Zero to Mastery [2023] + Clean Architecture](https://www.udemy.com/course/flutter-made-easy-zero-to-mastery/).

I assume the instructor wanted to get us understand more a state management, using  different solutions.
> I would go with Bloc/cubit as you have the option to switch to a event stream when there are multiple sources that can change the state from a bloc. we use cubit as default and only if we get problems with a cubit we go for bloc.

> For the theme changing logic I would go with a cubit.

> Provider is more lightweight to website , that's the reason why we using cubits from the bloc package to have there no disadvantage.

Hope it helps!

**Comment by shamxali** [comment]
@YamamotoDesu thank you for explaining.

Is this project open for contribution?

**Comment by YamamotoDesu** [comment]
@shamxali You are welcome, Sham.
Absolutely! I've sent an invite to this repo.
